/* DO NOT EDIT: This file is automatically generated by Cabal */

/* package Cabal-1.22.4.0 */
#define VERSION_Cabal "1.22.4.0"
#define MIN_VERSION_Cabal(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  22 || \
  (major1) == 1 && (major2) == 22 && (minor) <= 4)

/* package aeson-0.8.0.2 */
#define VERSION_aeson "0.8.0.2"
#define MIN_VERSION_aeson(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  8 || \
  (major1) == 0 && (major2) == 8 && (minor) <= 0)

/* package ansi-terminal-0.6.2.3 */
#define VERSION_ansi_terminal "0.6.2.3"
#define MIN_VERSION_ansi_terminal(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  6 || \
  (major1) == 0 && (major2) == 6 && (minor) <= 2)

/* package base-4.8.1.0 */
#define VERSION_base "4.8.1.0"
#define MIN_VERSION_base(major1,major2,minor) (\
  (major1) <  4 || \
  (major1) == 4 && (major2) <  8 || \
  (major1) == 4 && (major2) == 8 && (minor) <= 1)

/* package bytestring-0.10.6.0 */
#define VERSION_bytestring "0.10.6.0"
#define MIN_VERSION_bytestring(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  10 || \
  (major1) == 0 && (major2) == 10 && (minor) <= 6)

/* package containers-0.5.6.2 */
#define VERSION_containers "0.5.6.2"
#define MIN_VERSION_containers(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  5 || \
  (major1) == 0 && (major2) == 5 && (minor) <= 6)

/* package directory-1.2.2.0 */
#define VERSION_directory "1.2.2.0"
#define MIN_VERSION_directory(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  2 || \
  (major1) == 1 && (major2) == 2 && (minor) <= 2)

/* package ghc-7.10.2 */
#define VERSION_ghc "7.10.2"
#define MIN_VERSION_ghc(major1,major2,minor) (\
  (major1) <  7 || \
  (major1) == 7 && (major2) <  10 || \
  (major1) == 7 && (major2) == 10 && (minor) <= 2)

/* package ghc-paths-0.1.0.9 */
#define VERSION_ghc_paths "0.1.0.9"
#define MIN_VERSION_ghc_paths(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  1 || \
  (major1) == 0 && (major2) == 1 && (minor) <= 0)

/* package ghc-syb-utils-0.2.3 */
#define VERSION_ghc_syb_utils "0.2.3"
#define MIN_VERSION_ghc_syb_utils(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  2 || \
  (major1) == 0 && (major2) == 2 && (minor) <= 3)

/* package lens-simple-0.1.0.8 */
#define VERSION_lens_simple "0.1.0.8"
#define MIN_VERSION_lens_simple(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  1 || \
  (major1) == 0 && (major2) == 1 && (minor) <= 0)

/* package pipes-4.1.6 */
#define VERSION_pipes "4.1.6"
#define MIN_VERSION_pipes(major1,major2,minor) (\
  (major1) <  4 || \
  (major1) == 4 && (major2) <  1 || \
  (major1) == 4 && (major2) == 1 && (minor) <= 6)

/* package pipes-bytestring-2.1.1 */
#define VERSION_pipes_bytestring "2.1.1"
#define MIN_VERSION_pipes_bytestring(major1,major2,minor) (\
  (major1) <  2 || \
  (major1) == 2 && (major2) <  1 || \
  (major1) == 2 && (major2) == 1 && (minor) <= 1)

/* package pipes-files-0.1.1 */
#define VERSION_pipes_files "0.1.1"
#define MIN_VERSION_pipes_files(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  1 || \
  (major1) == 0 && (major2) == 1 && (minor) <= 1)

/* package pipes-group-1.0.3 */
#define VERSION_pipes_group "1.0.3"
#define MIN_VERSION_pipes_group(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  0 || \
  (major1) == 1 && (major2) == 0 && (minor) <= 3)

/* package pipes-safe-2.2.3 */
#define VERSION_pipes_safe "2.2.3"
#define MIN_VERSION_pipes_safe(major1,major2,minor) (\
  (major1) <  2 || \
  (major1) == 2 && (major2) <  2 || \
  (major1) == 2 && (major2) == 2 && (minor) <= 3)

/* package syb-0.5.1 */
#define VERSION_syb "0.5.1"
#define MIN_VERSION_syb(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  5 || \
  (major1) == 0 && (major2) == 5 && (minor) <= 1)

/* package docopt-0.7.0.4 */
#define VERSION_docopt "0.7.0.4"
#define MIN_VERSION_docopt(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  7 || \
  (major1) == 0 && (major2) == 7 && (minor) <= 0)

/* package QuickCheck-2.8.1 */
#define VERSION_QuickCheck "2.8.1"
#define MIN_VERSION_QuickCheck(major1,major2,minor) (\
  (major1) <  2 || \
  (major1) == 2 && (major2) <  8 || \
  (major1) == 2 && (major2) == 8 && (minor) <= 1)

/* package filepath-1.4.0.0 */
#define VERSION_filepath "1.4.0.0"
#define MIN_VERSION_filepath(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  4 || \
  (major1) == 1 && (major2) == 4 && (minor) <= 0)

/* package hspec-2.1.10 */
#define VERSION_hspec "2.1.10"
#define MIN_VERSION_hspec(major1,major2,minor) (\
  (major1) <  2 || \
  (major1) == 2 && (major2) <  1 || \
  (major1) == 2 && (major2) == 1 && (minor) <= 10)

/* package hlint-1.9.21 */
#define VERSION_hlint "1.9.21"
#define MIN_VERSION_hlint(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  9 || \
  (major1) == 1 && (major2) == 9 && (minor) <= 21)

/* tool cpphs-1.19.3 */
#define TOOL_VERSION_cpphs "1.19.3"
#define MIN_TOOL_VERSION_cpphs(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  19 || \
  (major1) == 1 && (major2) == 19 && (minor) <= 3)

/* tool gcc-5.2.0 */
#define TOOL_VERSION_gcc "5.2.0"
#define MIN_TOOL_VERSION_gcc(major1,major2,minor) (\
  (major1) <  5 || \
  (major1) == 5 && (major2) <  2 || \
  (major1) == 5 && (major2) == 2 && (minor) <= 0)

/* tool ghc-7.10.2 */
#define TOOL_VERSION_ghc "7.10.2"
#define MIN_TOOL_VERSION_ghc(major1,major2,minor) (\
  (major1) <  7 || \
  (major1) == 7 && (major2) <  10 || \
  (major1) == 7 && (major2) == 10 && (minor) <= 2)

/* tool ghc-pkg-7.10.2 */
#define TOOL_VERSION_ghc_pkg "7.10.2"
#define MIN_TOOL_VERSION_ghc_pkg(major1,major2,minor) (\
  (major1) <  7 || \
  (major1) == 7 && (major2) <  10 || \
  (major1) == 7 && (major2) == 10 && (minor) <= 2)

/* tool haddock-2.16.1 */
#define TOOL_VERSION_haddock "2.16.1"
#define MIN_TOOL_VERSION_haddock(major1,major2,minor) (\
  (major1) <  2 || \
  (major1) == 2 && (major2) <  16 || \
  (major1) == 2 && (major2) == 16 && (minor) <= 1)

/* tool happy-1.19.5 */
#define TOOL_VERSION_happy "1.19.5"
#define MIN_TOOL_VERSION_happy(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  19 || \
  (major1) == 1 && (major2) == 19 && (minor) <= 5)

/* tool hpc-0.67 */
#define TOOL_VERSION_hpc "0.67"
#define MIN_TOOL_VERSION_hpc(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  67 || \
  (major1) == 0 && (major2) == 67 && (minor) <= 0)

/* tool hsc2hs-0.67 */
#define TOOL_VERSION_hsc2hs "0.67"
#define MIN_TOOL_VERSION_hsc2hs(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  67 || \
  (major1) == 0 && (major2) == 67 && (minor) <= 0)

/* tool hscolour-1.22 */
#define TOOL_VERSION_hscolour "1.22"
#define MIN_TOOL_VERSION_hscolour(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  22 || \
  (major1) == 1 && (major2) == 22 && (minor) <= 0)

/* tool pkg-config-0.29 */
#define TOOL_VERSION_pkg_config "0.29"
#define MIN_TOOL_VERSION_pkg_config(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  29 || \
  (major1) == 0 && (major2) == 29 && (minor) <= 0)

/* tool strip-2.25 */
#define TOOL_VERSION_strip "2.25"
#define MIN_TOOL_VERSION_strip(major1,major2,minor) (\
  (major1) <  2 || \
  (major1) == 2 && (major2) <  25 || \
  (major1) == 2 && (major2) == 25 && (minor) <= 0)

#define CURRENT_PACKAGE_KEY "argon_EPnFAvdLsdbDHKR24nicp7"

